/**
 * Bundled airport database (coordinates + runways) for on-device pack building.
 * The OFP (or the pilot) supplies idents; this supplies each field's position
 * and runways so a briefing pack assembles with no navigation-data fetch.
 *
 * Generated by scripts/build-airport-db.mjs from OurAirports (CC0). Not a
 * certified navigation database.
 */
import raw from './airport-db.json';
import { distanceNm, crossTrackNm, alongTrackNm } from '../core/geo.js';
import type { BriefingAirport } from './briefing.js';
import type { LatLon } from '../core/types.js';

type Runway = [string, number]; // [designator e.g. "16L", true heading deg]
type Row = [string, number, number, string, number, number, number, Runway[], string, number];
interface DbFile {
  fmt: string[];
  airports: Row[];
  /** Legacy-ident -> current-id, so an old code still resolves (UTTT -> UZTT). */
  aliases?: Record<string, string>;
}

const byId = new Map<string, BriefingAirport>();
for (const [ident, lat, lon, name, elevFt, rwyFt, hard, runways, tz, atis] of (
  raw as unknown as DbFile
).airports) {
  const hasRwy = runways && runways.length > 0;
  byId.set(ident, {
    ident,
    name,
    lat,
    lon,
    elevFt: elevFt || undefined,
    longestRwyFt: rwyFt || undefined,
    hardSurface: hard === 1,
    runways: hasRwy ? runways : undefined,
    runwayHeadingsDeg: hasRwy ? [...new Set(runways.map((r) => r[1]))] : undefined,
    tz: tz || undefined,
    atisMhz: atis || undefined,
  });
}

const aliases = new Map<string, string>(Object.entries((raw as unknown as DbFile).aliases ?? {}));

export function dbAirportCount(): number {
  return byId.size;
}

/** Look up a bundled airport by ICAO ident (case-insensitive), following the
 *  legacy-code alias table when a reassigned code is typed (e.g. UTTT -> UZTT). */
export function dbAirport(ident: string): BriefingAirport | undefined {
  const id = ident.trim().toUpperCase();
  const hit = byId.get(id);
  if (hit) return hit;
  const aliased = aliases.get(id);
  return aliased ? byId.get(aliased) : undefined;
}

const M_PER_FT = 0.3048;

/**
 * A320-capable fields lying within a corridor of the dep→dest great circle —
 * the en-route alternates to auto-add when the pilot only types dep/dest.
 * `maxOffsetNm` is the cross-track half-width; results are nearest-to-route
 * first and capped at `limit`.
 */
export function corridorAlternates(
  dep: LatLon,
  dest: LatLon,
  opts: { maxOffsetNm?: number; minRwyM?: number; limit?: number; exclude?: Set<string> } = {},
): BriefingAirport[] {
  const maxOffset = opts.maxOffsetNm ?? 250;
  const minRwyM = opts.minRwyM ?? 2000;
  const legLen = distanceNm(dep, dest);
  const exclude = opts.exclude ?? new Set<string>();

  const out: Array<{ a: BriefingAirport; offset: number }> = [];
  for (const a of byId.values()) {
    if (exclude.has(a.ident)) continue;
    if (!a.hardSurface || a.longestRwyFt == null || a.longestRwyFt * M_PER_FT < minRwyM) continue;
    const along = alongTrackNm(a, dep, dest);
    if (along < -20 || along > legLen + 20) continue; // roughly between the ends
    const offset = Math.abs(crossTrackNm(a, dep, dest));
    if (offset > maxOffset) continue;
    out.push({ a, offset });
  }
  out.sort((x, y) => x.offset - y.offset);
  return out.slice(0, opts.limit ?? 12).map((x) => x.a);
}
